apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deploy
spec:
  replicas: 10
  template:
    metadata:
      name: new-deploy-pod
      labels:
        app: test-svc
    spec:
      containers:
        - image: nginx
          name: deploynginx
  selector:
    matchLabels:
      app: test-svc

# image: nginx:1.21

