apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deply
spec:
  replicas: 1
  template:
    metadata:
      name: my-pod
      labels:
        env: test
    spec:
      containers:
      - name: nginxcon
        image: nginx
      nodeSelector:
        disktype: ssd
  selector:
    matchLabels:
      env: test
