apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvdemo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 54.75.15.157                 # check this everytime
    path: /opt/sfw/
    readOnly: false
