apiVersion: v1
kind: ReplicationController
metadata:
  name: new-rc
spec:
  replicas: 2
  template:
    metadata:
      name: new-pod
      labels:
        course: k8s
    spec:
      containers:
      - name: c1
        image: nginx
