apiVersion: v1
kind: ReplicationController
metadata:
  name: new-rc-test
spec:
  replicas: 2
  template:
    metadata:
      name: firstpod
      labels:
        course: white
    spec:
      containers:
      - name: c1
        image: nginx
