apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-toleration
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - image: nginx
          name: tolercon
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "blue"
          effect: "NoSchedule"
      #nodeSelector:
         #colour: blue
