apiVersion: v1
kind: Pod
metadata:
  name: volume-po
spec:
  containers:
    - image: busybox
      name: busybox
      command: ['sh', '-c', 'while true; do echo siva!!!! >> /output/output.txt; sleep5; done']
      volumeMounts:
        - name: my-volume
          mountPath: /output
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: nfs-pvc-claim
